meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: iot-haproxy_leader_z1
    templates:
    - name: iot-haproxy
      release: iot-haproxy
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    properties: {}
  - name: iot-haproxy_z1
    templates:
    - name: iot-haproxy
      release: iot-haproxy
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      ha_proxy:
        config_file: /var/vcap/store/consul-template/haproxy.config
      consul_template:
        output_file: /var/vcap/store/consul-template/haproxy.config
      iot-haproxy:
        leader_address: (( merge ))

networks: (( merge ))

properties: {}
